logging:
  level:
    root:
      org.springframework.web: INFO

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:playlistdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    driverClassName: org.h2.Driver
  jpa:
    show_sql: true
    defer-datasource-initialization: true
  main:
    allow-bean-definition-overriding: true